export const ADD_NEXT_ID_TO_LOCALSTORAGE = 'ADD_NEXT_ID_TO_LOCALSTORAGE';
export const SHOW_FRUITS = 'SHOW_FRUITS';
export const SHOW_VEGETABLES = 'SHOW_VEGETABLES';
export const SHOW_JUICES = 'SHOW_JUICES';
export const SHOW_DAIRY_PRODUCTS = 'SHOW_DAIRY_PRODUCTS';