export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_NEXT_PRODUCT = 'ADD_NEXT_PRODUCT';
export const ADD_NEXT_ID_TO_LOCALSTORAGE = 'ADD_NEXT_ID_TO_LOCALSTORAGE';
export const SHOW_FRUITS = 'SHOW_FRUITS';