export const ADD_NEXT_ID_TO_LOCALSTORAGE = 'ADD_NEXT_ID_TO_LOCALSTORAGE';
export const SHOW_FRUITS = 'SHOW_FRUITS';
export const SHOW_VEGETABLES = 'SHOW_VEGETABLES';
export const SHOW_JUICES = 'SHOW_JUICES';
export const SHOW_DAIRY_PRODUCTS = 'SHOW_DAIRY_PRODUCTS';
export const SHOW_OILS = 'SHOW_OILS';
export const SHOW_SHOPPING_BASKET_POPUP = 'SHOW_SHOPPING_BASKET_POPUP';
export const DEL_ID_ELEMENT = 'DEL_ID_ELEMENT';